### ISSUE TITLE
supports `.d.ts` ?

### ISSUE THREAD

**Issue by viliusl** [wix/okidoc#7]
```bash
(master *)$ node_modules/.bin/okidoc index.d.ts

/node_modules/yamljs/lib/Parser.js:404
            throw e;
            ^
Error: Unexpected characters near ";".
```

**Comment by bodia-uz** [comment]
Looks like the problem is in invalid script run.
Try `okidoc ./docs.yml ./docs`
With config like
```yaml
# ./docs.yml
- path: test.md
  title: Test
  glob: docs/*.ts
  tag: Test
```

Read https://wix.github.io/okidoc/#generate-documentation for details
