### ISSUE TITLE
Parsing of typescript generic constraints fails

### ISSUE THREAD

**Issue by DenHaidash** [wix/okidoc#77]
**okidoc-md** process fails if code contains [Generic constraints](https://www.typescriptlang.org/docs/handbook/generics.html#generic-constraints)

<img width="1125" alt="Screenshot 2020-08-26 at 15 41 43" src="https://user-images.githubusercontent.com/4649956/91304783-b845d280-e7b2-11ea-814d-3c26490ee30a.png">

**Conditions**:
```
"okidoc-md": "2.0.0"
```

**doc-config.yml**
```yml
- path: Example/Example.md
  title: example
  glob: ./*.ts
  tag: Example
```

**index.ts**
```typescript
export type Config = {
    path: string
}

/**
 * @doc Example
 * @example doSmth<Config>({ path: '.' })
 * @param param - param
 */
export function doSmth<T extends Config>(param: T): void {}
```
